"""0002_add_client_event_id

Revision ID: 1d69fffd1e6b
Revises: cfe827193ef4
Create Date: 2026-06-19 00:48:56.538946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1d69fffd1e6b'
down_revision: Union[str, None] = 'cfe827193ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('client_event_id', sa.String(length=64), nullable=True, comment='Client-generated idempotency key'))
    op.create_index(op.f('ix_events_client_event_id'), 'events', ['client_event_id'], unique=True)
    op.alter_column('users', 'price_preference',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'price_preference',
               existing_type=sa.String(length=32),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_events_client_event_id'), table_name='events')
    op.drop_column('events', 'client_event_id')
    # ### end Alembic commands ###
