"""0001_initial_schema

Revision ID: cfe827193ef4
Revises: 
Create Date: 2026-06-18 19:40:54.864548
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'cfe827193ef4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=128), nullable=False, comment='Human-readable dataset label'),
    sa.Column('dataset_fingerprint', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of dataset content'),
    sa.Column('source_path', sa.String(length=1024), nullable=True, comment='Directory path used for import (audit only)'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.Column('queries_count', sa.Integer(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('qrels_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True, comment="Error details if status is 'failed'"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_dataset_fingerprint'), 'import_runs', ['dataset_fingerprint'], unique=False)
    op.create_index('ix_import_runs_fingerprint_status', 'import_runs', ['dataset_fingerprint', 'status'], unique=False)
    op.create_index('ix_import_runs_started_at', 'import_runs', ['started_at'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('subcategory', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Item price in arbitrary currency units'),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('popularity_score >= 0 AND popularity_score <= 1', name='ck_item_popularity_score_range'),
    sa.CheckConstraint('price >= 0', name='ck_item_price_non_negative'),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 1', name='ck_item_quality_score_range'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_brand'), 'items', ['brand'], unique=False)
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index('ix_items_created_at', 'items', ['created_at'], unique=False)
    op.create_index(op.f('ix_items_is_cold_start'), 'items', ['is_cold_start'], unique=False)
    op.create_index(op.f('ix_items_subcategory'), 'items', ['subcategory'], unique=False)
    op.create_table('queries',
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('intended_category', sa.String(length=128), nullable=True),
    sa.Column('semantic_intent', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('ix_queries_created_at', 'queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_queries_intended_category'), 'queries', ['intended_category'], unique=False)
    op.create_index(op.f('ix_queries_query_text'), 'queries', ['query_text'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('preferred_categories', sa.JSON(), nullable=False, comment='JSON array of preferred category strings'),
    sa.Column('preferred_brands', sa.JSON(), nullable=False, comment='JSON array of preferred brand strings'),
    sa.Column('price_preference', sa.Float(), nullable=True, comment='Preferred price point from MVP data'),
    sa.Column('activity_level', sa.String(length=32), nullable=True, comment='Activity level (e.g. low, medium, high)'),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_activity_level'), 'users', ['activity_level'], unique=False)
    op.create_index(op.f('ix_users_is_cold_start'), 'users', ['is_cold_start'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=True, comment='Nullable — impressions may not reference a query'),
    sa.Column('query_text', sa.String(length=512), nullable=True),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('click_duration_ms', sa.Integer(), nullable=True),
    sa.Column('add_to_cart_quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint("event_type IN ('add_to_cart', 'click', 'favorite', 'impression', 'purchase')", name='ck_event_type_valid'),
    sa.CheckConstraint('add_to_cart_quantity IS NULL OR add_to_cart_quantity >= 0', name='ck_event_cart_quantity_non_negative'),
    sa.CheckConstraint('click_duration_ms IS NULL OR click_duration_ms >= 0', name='ck_event_click_duration_non_negative'),
    sa.CheckConstraint('position IS NULL OR position > 0', name='ck_event_position_positive'),
    sa.CheckConstraint('purchase_amount IS NULL OR purchase_amount >= 0', name='ck_event_purchase_amount_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.query_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_item_id'), 'events', ['item_id'], unique=False)
    op.create_index(op.f('ix_events_query_id'), 'events', ['query_id'], unique=False)
    op.create_index('ix_events_query_timestamp', 'events', ['query_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_request_id'), 'events', ['request_id'], unique=False)
    op.create_index('ix_events_request_position', 'events', ['request_id', 'position'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index('ix_events_user_timestamp', 'events', ['user_id', 'timestamp'], unique=False)
    op.create_table('qrels',
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('relevance_grade', sa.Integer(), nullable=False, comment='Relevance grade 1–3 (3 = most relevant)'),
    sa.CheckConstraint('relevance_grade >= 1 AND relevance_grade <= 3', name='ck_qrel_relevance_grade_range'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.query_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('query_id', 'item_id'),
    sa.UniqueConstraint('query_id', 'item_id', name='uq_qrel_query_item')
    )
    op.create_index(op.f('ix_qrels_item_id'), 'qrels', ['item_id'], unique=False)
    op.create_index(op.f('ix_qrels_query_id'), 'qrels', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qrels_query_id'), table_name='qrels')
    op.drop_index(op.f('ix_qrels_item_id'), table_name='qrels')
    op.drop_table('qrels')
    op.drop_index('ix_events_user_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index('ix_events_request_position', table_name='events')
    op.drop_index(op.f('ix_events_request_id'), table_name='events')
    op.drop_index('ix_events_query_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_query_id'), table_name='events')
    op.drop_index(op.f('ix_events_item_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_is_cold_start'), table_name='users')
    op.drop_index(op.f('ix_users_activity_level'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_queries_query_text'), table_name='queries')
    op.drop_index(op.f('ix_queries_intended_category'), table_name='queries')
    op.drop_index('ix_queries_created_at', table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_items_subcategory'), table_name='items')
    op.drop_index(op.f('ix_items_is_cold_start'), table_name='items')
    op.drop_index('ix_items_created_at', table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_index(op.f('ix_items_brand'), table_name='items')
    op.drop_table('items')
    op.drop_index('ix_import_runs_started_at', table_name='import_runs')
    op.drop_index('ix_import_runs_fingerprint_status', table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_dataset_fingerprint'), table_name='import_runs')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
